[package]
name = "dual-mtr-ctrlr"
publish.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
cu-bincode = { workspace = true }
serde = { workspace = true }
cu-pid = { workspace = true }
