[package]
name = "zenoh-session"
publish.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
keywords.workspace = true

[dependencies]
zenoh = { workspace = true }
