[package]
name = "cu-hcsr04"
version = "0.1.0"
edition = "2024"

[dependencies]
cu29 = { workspace = true }
cu-bincode = { workspace = true }
serde = { workspace = true }
hcsr04-gpio-cdev = { workspace = true }

[build-dependencies]
cfg_aliases = "0.2.1"
