[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
# rustflags = ["-C", "link-arg=-fuse-ld=bfd"]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[env]
BAZEL_BINDGEN_PATH_CORRECTION = ""
# BINDGEN_EXTRA_CLANG_ARGS="--sysroot=/opt/homebrew/bin/zig --target=aarch64-unknown-linux-gnu"
